select * from clarity_fc
select * from clarity_eap
select * from clarity_loc
select * from hsp_account
select * from or_log
select * from order_proc 
select * from order_results
select * from pat_enc
select * from pat_enc_hsp
select * from pat_or_adm_link
select * from patient
select * from res_components
select * from spec_db_main
select * from v_case_volume
select * from v_lab_results
select * from zc_order_status
select * from zc_spec_source

-- adding primary keys
ALTER TABLE clarity_fc
ADD CONSTRAINT clarity_fc_pk PRIMARY KEY (FINANCIAL_CLASS);
ALTER TABLE clarity_eap
ADD CONSTRAINT clarity_eap_pk PRIMARY KEY (PROC_ID);
ALTER TABLE clarity_loc
ADD CONSTRAINT clarity_loc_pk PRIMARY KEY (LOC_ID);
-- ALTER TABLE hsp_account ADD CONSTRAINT hsp_account_pk PRIMARY KEY ("HSP_ACCOUNT_ID");
ALTER TABLE or_log
ADD CONSTRAINT or_log_pk PRIMARY KEY (LOG_ID);
ALTER TABLE order_proc
ADD CONSTRAINT order_proc_pk PRIMARY KEY (ORDER_PROC_ID);
ALTER TABLE order_results
ADD CONSTRAINT order_results_pk PRIMARY KEY (ORDER_PROC_ID,ORD_DATE_REAL,LINE);
ALTER TABLE pat_enc
ADD CONSTRAINT pat_enc_pk PRIMARY KEY (PAT_ENC_CSN_ID);
ALTER TABLE pat_enc_hsp
ADD CONSTRAINT pat_enc_hsp_pk PRIMARY KEY (PAT_ENC_CSN_ID);
ALTER TABLE pat_or_adm_link
ADD CONSTRAINT pat_or_adm_link_pk PRIMARY KEY (PAT_ENC_CSN_ID);
ALTER TABLE patient
ADD CONSTRAINT patient_pk PRIMARY KEY (PAT_ID);
ALTER TABLE res_components
ADD CONSTRAINT res_components_pk PRIMARY KEY (RESULT_ID,LINE);
ALTER TABLE spec_db_main
ADD CONSTRAINT spec_db_main_pk PRIMARY KEY (SPECIMEN_ID);
ALTER TABLE v_case_volume
ADD CONSTRAINT v_case_volume_pk PRIMARY KEY (LOG_ID);
ALTER TABLE v_lab_results
ADD CONSTRAINT v_lab_results_pk PRIMARY KEY (RESULT_ID,TEST_ID,TEST_LINE,SPECIMEN_ID);
ALTER TABLE zc_order_status
ADD CONSTRAINT zc_order_status_pk PRIMARY KEY (ORDER_STATUS_C);
ALTER TABLE zc_spec_source
ADD CONSTRAINT zc_spec_source_pk PRIMARY KEY (SPEC_SOURCE_C);


-- column type conversion

ALTER TABLE order_proc
ALTER COLUMN SERV_AREA_ID TYPE bigint;

ALTER TABLE patient
ALTER COLUMN PRIM_FC TYPE bigint;

ALTER TABLE pat_enc
ALTER COLUMN PRIMARY_LOC_ID TYPE bigint,
ALTER COLUMN VISIT_FC TYPE bigint;

ALTER TABLE hsp_account
ALTER COLUMN DISCH_LOC_ID TYPE bigint;

ALTER TABLE order_results
ALTER COLUMN SERV_AREA_ID TYPE bigint;


-- foreign keys
ALTER TABLE order_proc
ADD CONSTRAINT FK_order_proc_Patient
FOREIGN KEY (PAT_ID) REFERENCES PATIENT(PAT_ID),
ADD CONSTRAINT FK_order_proc_PAT_ENC
FOREIGN KEY (PAT_ENC_CSN_ID) REFERENCES PAT_ENC(PAT_ENC_CSN_ID),
/*ADD CONSTRAINT FK_order_proc_PAT_ENC_HSP
FOREIGN KEY (PAT_ENC_CSN_ID) REFERENCES PAT_ENC_HSP(PAT_ENC_CSN_ID),
ADD CONSTRAINT FK_order_proc_PAT_OR_ADM_LINK
FOREIGN KEY (PAT_ENC_CSN_ID) REFERENCES PAT_OR_ADM_LINK(PAT_ENC_CSN_ID),*/
ADD CONSTRAINT FK_order_proc_CLARITY_EAP
FOREIGN KEY (PROC_ID) REFERENCES CLARITY_EAP(PROC_ID),
ADD CONSTRAINT FK_order_proc_ZC_ORDER_STATUS
FOREIGN KEY (ORDER_STATUS_C) REFERENCES ZC_ORDER_STATUS(ORDER_STATUS_C),
ADD CONSTRAINT FK_order_proc_CLARITY_LOC
FOREIGN KEY (SERV_AREA_ID) REFERENCES CLARITY_LOC(LOC_ID);

ALTER TABLE patient
ADD CONSTRAINT FK_patient_CLARITY_FC
FOREIGN KEY (PRIM_FC) REFERENCES CLARITY_FC(FINANCIAL_CLASS);


ALTER TABLE pat_enc
ADD CONSTRAINT FK_pat_enc_patient
FOREIGN KEY (PAT_ID) REFERENCES patient(PAT_ID),
/*ADD CONSTRAINT FK_pat_enc_PAT_ENC_HSP
FOREIGN KEY (PAT_ENC_CSN_ID) REFERENCES PAT_ENC_HSP(PAT_ENC_CSN_ID),
ADD CONSTRAINT FK_pat_enc_PAT_OR_ADM_LINK
FOREIGN KEY (PAT_ENC_CSN_ID) REFERENCES PAT_OR_ADM_LINK(PAT_ENC_CSN_ID),
ADD CONSTRAINT FK_pat_enc_CLARITY_LOC
FOREIGN KEY (PRIMARY_LOC_ID) REFERENCES CLARITY_LOC(LOC_ID),*/
ADD CONSTRAINT FK_pat_enc_CLARITY_FC
FOREIGN KEY (VISIT_FC) REFERENCES CLARITY_FC(FINANCIAL_CLASS),
ADD CONSTRAINT FK_pat_enc_CLARITY_LOC2
FOREIGN KEY (SERV_AREA_ID) REFERENCES CLARITY_LOC(LOC_ID);

ALTER TABLE pat_enc_hsp
ADD CONSTRAINT FK_pat_enc_hsp_patient
FOREIGN KEY (PAT_ID) REFERENCES patient(PAT_ID),
ADD CONSTRAINT FK_pat_enc_hsp_PAT_ENC
FOREIGN KEY (PAT_ENC_CSN_ID) REFERENCES PAT_ENC(PAT_ENC_CSN_ID),
ADD CONSTRAINT FK_pat_enc_hsp_CLARITY_LOC
FOREIGN KEY (HOSPITAL_AREA_ID) REFERENCES CLARITY_LOC(LOC_ID);

ALTER TABLE hsp_account
ADD CONSTRAINT FK_hsp_account_CLARITY_FC
FOREIGN KEY (ACCT_FIN_CLASS_C) REFERENCES CLARITY_FC(FINANCIAL_CLASS),
/*ADD CONSTRAINT FK_hsp_account_CLARITY_LOC
FOREIGN KEY (DISCH_LOC_ID) REFERENCES CLARITY_LOC(LOC_ID),
ADD CONSTRAINT FK_hsp_account_CLARITY_LOC2
FOREIGN KEY (LOC_ID) REFERENCES CLARITY_LOC(LOC_ID),*/
ADD CONSTRAINT FK_hsp_account_PATIENT
FOREIGN KEY (PAT_ID) REFERENCES PATIENT(PAT_ID),
ADD CONSTRAINT FK_hsp_account_CLARITY_LOC3
FOREIGN KEY (SERV_AREA_ID) REFERENCES CLARITY_LOC(LOC_ID)/*,
ADD CONSTRAINT FK_hsp_account_PAT_ENC
FOREIGN KEY (PRIM_ENC_CSN_ID) REFERENCES PAT_ENC(PRIM_ENC_CSN_ID),
ADD CONSTRAINT FK_hsp_account_PAT_ENC_HSP
FOREIGN KEY (PRIM_ENC_CSN_ID) REFERENCES PAT_ENC_HSP(PRIM_ENC_CSN_ID),
ADD CONSTRAINT FK_hsp_account_PAT_OR_ADM_LINK
FOREIGN KEY (PRIM_ENC_CSN_ID) REFERENCES PAT_OR_ADM_LINK(PRIM_ENC_CSN_ID)*/;

ALTER TABLE or_log
ADD CONSTRAINT FK_or_log_V_CASE_VOLUME
FOREIGN KEY (LOG_ID) REFERENCES V_CASE_VOLUME(LOG_ID),
ADD CONSTRAINT FK_or_log_PATIENT
FOREIGN KEY (PAT_ID) REFERENCES PATIENT(PAT_ID),
ADD CONSTRAINT FK_or_log_CLARITY_LOC
FOREIGN KEY (LOC_ID) REFERENCES CLARITY_LOC(LOC_ID);

ALTER TABLE V_CASE_VOLUME
ADD CONSTRAINT FK_V_CASE_VOLUME_OR_LOG
FOREIGN KEY (LOG_ID) REFERENCES OR_LOG(LOG_ID),
ADD CONSTRAINT FK_V_CASE_VOLUME_PATIENT
FOREIGN KEY (PAT_ID) REFERENCES PATIENT(PAT_ID),
ADD CONSTRAINT FK_V_CASE_VOLUME_CLARITY_LOC
FOREIGN KEY (LOCATION_ID) REFERENCES CLARITY_LOC(LOC_ID);

ALTER TABLE pat_or_adm_link
/*ADD CONSTRAINT FK_pat_or_adm_link_PAT_ENC
FOREIGN KEY (PAT_ENC_CSN_ID) REFERENCES PAT_ENC(PAT_ENC_CSN_ID),
ADD CONSTRAINT FK_pat_or_adm_link_PAT_ENC_HSP
FOREIGN KEY (PAT_ENC_CSN_ID) REFERENCES PAT_ENC_HSP(PAT_ENC_CSN_ID),*/
ADD CONSTRAINT FK_pat_or_adm_link_PATIENT
FOREIGN KEY (PAT_ID) REFERENCES PATIENT(PAT_ID),
/*ADD CONSTRAINT FK_pat_or_adm_link_PAT_ENC2
FOREIGN KEY (OR_LINK_CSN) REFERENCES PAT_ENC(PAT_ENC_CSN_ID),
ADD CONSTRAINT FK_pat_or_adm_link_PAT_ENC_HSP2
FOREIGN KEY (OR_LINK_CSN) REFERENCES PAT_ENC_HSP(PAT_ENC_CSN_ID),*/
ADD CONSTRAINT FK_pat_or_adm_link_OR_LOG
FOREIGN KEY (LOG_ID) REFERENCES OR_LOG(LOG_ID),
ADD CONSTRAINT FK_pat_or_adm_link_V_CASE_VOLUME
FOREIGN KEY (LOG_ID) REFERENCES V_CASE_VOLUME(LOG_ID);

ALTER TABLE v_lab_results
ADD CONSTRAINT FK_v_lab_results_PATIENT
FOREIGN KEY (EPT_PATIENT_ID) REFERENCES PATIENT(PAT_ID)/*,
ADD CONSTRAINT FK_v_lab_results_ORDER_PROC
FOREIGN KEY (ORDER_ID) REFERENCES ORDER_PROC(ORDER_PROC_ID),
ADD CONSTRAINT FK_v_lab_results_CLARITY_EAP
FOREIGN KEY (PROC_ID) REFERENCES CLARITY_EAP(PROC_ID),
ADD CONSTRAINT FK_v_lab_results_PAT_ENC
FOREIGN KEY (PAT_ENC_CSN_ID) REFERENCES PAT_ENC(PAT_ENC_CSN_ID),
ADD CONSTRAINT FK_v_lab_results_PAT_ENC_HSP
FOREIGN KEY (PAT_ENC_CSN_ID) REFERENCES PAT_ENC_HSP(PAT_ENC_CSN_ID),
ADD CONSTRAINT FK_v_lab_results_PAT_OR_ADM_LINK
FOREIGN KEY (PAT_ENC_CSN_ID) REFERENCES PAT_OR_ADM_LINK(PAT_ENC_CSN_ID)*/;

ALTER TABLE spec_db_main
ADD CONSTRAINT FK_spec_db_main_ZC_SPEC_SOURCE
FOREIGN KEY (SPEC_SOURCE_C) REFERENCES ZC_SPEC_SOURCE(SPEC_SOURCE_C)/*,
ADD CONSTRAINT FK_spec_db_main_PATIENT
FOREIGN KEY (SPEC_EPT_PAT_ID) REFERENCES PATIENT(PAT_ID)*/;

ALTER TABLE order_results
ADD CONSTRAINT FK_order_results_ORDER_PROC
FOREIGN KEY (ORDER_PROC_ID) REFERENCES ORDER_PROC(ORDER_PROC_ID),
ADD CONSTRAINT FK_order_results_PAT_ENC
FOREIGN KEY (PAT_ENC_CSN_ID) REFERENCES PAT_ENC(PAT_ENC_CSN_ID),
/*ADD CONSTRAINT FK_order_results_PAT_ENC_HSP
FOREIGN KEY (PAT_ENC_CSN_ID) REFERENCES PAT_ENC_HSP(PAT_ENC_CSN_ID),
ADD CONSTRAINT FK_order_results_PAT_OR_ADM_LINK
FOREIGN KEY (PAT_ENC_CSN_ID) REFERENCES PAT_OR_ADM_LINK(PAT_ENC_CSN_ID),*/
ADD CONSTRAINT FK_order_results_CLARITY_LOC
FOREIGN KEY (SERV_AREA_ID) REFERENCES CLARITY_LOC(LOC_ID);


